version: "3"
services:
    db:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=sample
        - POSTGRES_USER=sample
        - POSTGRES_DB=sample
      volumes:
        - sample_db:/var/lib/postgresql/data
      networks:
        - microservicios
      restart: always
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 8080
      labels:
        traefik.port: 8080
      restart: always
      depends_on:
        - db
      networks:
        - microservicios
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
          - "traefik.frontend.port=3000"
      restart: always
      depends_on:
        - backend
        - db
      networks:
        - microservicios
    webserver:
      image: nginx:alpine
      restart: always
      volumes:
          - ./nginx:/etc/nginx/
      ports:
        - "80:80"
        - "8080:8080"
        - "3000:3000"
        - "443:443"
      networks:
        - microservicios
volumes:
  sample_db: {}
networks:
  microservicios:
# "--providers.docker.exposedbydefault=false"